export default [
    {
      id: 1,
      subject: "Mobile App Development",
      location: "Hendon",
      price: 200,
      spaces: 5,
      image: "./img/10.svg",
    },
    {
      id: 2,
      subject: "Business Intelligence",
      location: "Cricklewood",
      price: 300,
      spaces: 5,
      image: "./img/10.svg",
    },
    {
      id: 3,
      subject: "Web Development with Big Data",
      location: "Wembley",
      price: 350,
      spaces: 5,
      image: "./img/10.svg",
    },
    {
      id: 4,
      subject: "Artificial Intelligence",
      location: "Brent Cross",
      price: 100,
      spaces: 5,
      image: "./img/10.svg",
    },
    {
      id: 5,
      subject: "Strategic Information Systems",
      location: "Camden",
      price: 250,
      spaces: 5,
      image: "./img/10.svg",
    },
    {
      id: 6,
      subject: "UX Design",
      location: "Colindale",
      price: 150,
      spaces: 5,
      image: "./img/10.svg",
    },
    {
      id: 7,
      subject: "Computer Technology",
      location: "London Bridge",
      price: 200,
      spaces: 5,
      image: "./img/10.svg",
    },
    {
      id: 8,
      subject: "Digital Media Technology",
      location: "Edgware",
      price: 400,
      spaces: 5,
      image: "./img/10.svg",
    },
    {
      id: 9,
      subject: "Cybersecurity",
      location: "Chelsea",
      price: 850,
      spaces: 5,
      image: "./img/10.svg",
    },
    {
      id: 10,
      subject: "Deep Learning and Computer Vision",
      location: "Watford",
      price: 800,
      spaces: 5,
      image: "./img/10.svg",
    },
  ]

