export default [
    {
      id: 1,
      subject: "Mobile App Development",
      location: "Hendon",
      price: 200,
      spaces: 5,
      image: "./img/pic10.png",
    },
    {
      id: 2,
      subject: "Business Intelligence",
      location: "Cricklewood",
      price: 300,
      spaces: 5,
      image: "./img/pic9.png",
    },
    {
      id: 3,
      subject: "Web Development with Big Data",
      location: "Wembley",
      price: 350,
      spaces: 5,
      image: "./img/pic8.png",
    },
    {
      id: 4,
      subject: "Artificial Intelligence",
      location: "Brent Cross",
      price: 100,
      spaces: 5,
      image: "./img/pic7.png",
    },
    {
      id: 5,
      subject: "Strategic Information Systems",
      location: "Camden",
      price: 250,
      spaces: 5,
      image: "./img/pic6.png",
    },
    {
      id: 6,
      subject: "UX Design",
      location: "Colindale",
      price: 150,
      spaces: 5,
      image: "./img/pic5.png",
    },
    {
      id: 7,
      subject: "Computer Technology",
      location: "London Bridge",
      price: 200,
      spaces: 5,
      image: "./img/pic4.png",
    },
    {
      id: 8,
      subject: "Digital Media Technology",
      location: "Edgware",
      price: 400,
      spaces: 5,
      image: "./img/pic3.png",
    },
    {
      id: 9,
      subject: "Cybersecurity",
      location: "Chelsea",
      price: 850,
      spaces: 5,
      image: "./img/pic2.png",
    },
    {
      id: 10,
      subject: "Deep Learning and Computer Vision",
      location: "Watford",
      price: 800,
      spaces: 5,
      image: "./img/pic1.png",
    },
  ]

